import { useState, type FormEvent } from 'react';
import { apiFetch, useAuth } from '../../../auth';
import { useLang } from '../../../i18n';
import { Button } from '../../../components/ui/Button';
import { FormActions } from '../../../components/ui/FormActions';
import { Notice } from '../../../components/ui/Notice';
import { textInputClassName } from '../../../components/ui/Field';
import { useUnsavedChanges } from '../../../components/ui/UnsavedChanges';

export function AccountSettings({displayName}:{displayName:string}):JSX.Element {
  const {lang}=useLang();const ar=lang==='ar';const {reload}=useAuth(); const label=(a:string,e:string)=>ar?a:e;
  const [name,setName]=useState(displayName);const [baseline,setBaseline]=useState(displayName);const [current,setCurrent]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');
  useUnsavedChanges(name!==baseline || !!(current || password || confirm),label('توجد تغييرات حساب غير محفوظة. هل تريد تركها؟','You have unsaved account changes. Leave without saving?'));
  async function save(event:FormEvent<HTMLFormElement>,changePassword:boolean):Promise<void>{event.preventDefault();if(busy || !event.currentTarget.reportValidity())return;setError('');setSuccess('');if(changePassword && password!==confirm){setError(label('كلمتا المرور غير متطابقتين.','Passwords do not match.'));return;}setBusy(true);try{await apiFetch('/auth/profile',{method:'PATCH',body:changePassword?{currentPassword:current,password}:{displayName:name}});if(changePassword){setCurrent('');setPassword('');setConfirm('');setSuccess(label('تم تغيير كلمة المرور وتسجيل خروج الجلسات الأخرى.','Password changed. Other sessions were signed out.'));}else{setBaseline(name);setSuccess(label('تم حفظ اسمك.','Your name was saved.'));}await reload();}catch{setError(changePassword?label('تعذر تغيير كلمة المرور. تحقق من كلمة المرور الحالية وحاول مجددًا.','Could not change your password. Check the current password and retry.'):label('تعذر حفظ الاسم. راجع البيانات وحاول مجددًا.','Could not save your name. Check the value and retry.'));}finally{setBusy(false);}}
  return <section className="my-6 space-y-4 border-t border-border pt-5" data-testid="account-settings"><h2 className="text-xl font-bold">{label('إعدادات الحساب','Account settings')}</h2>{error?<Notice kind="error">{error}</Notice>:null}{success?<Notice kind="success">{success}</Notice>:null}
    <form onSubmit={e=>void save(e,false)} className="space-y-3"><label className="block">{label('اسم العرض','Display name')}<input required minLength={2} maxLength={100} className={textInputClassName(false)} value={name} onChange={e=>setName(e.target.value)} /></label><FormActions><Button type="submit" disabled={busy}>{label('حفظ الاسم','Save name')}</Button></FormActions></form>
    <details><summary className="cursor-pointer font-bold">{label('تغيير كلمة المرور','Change password')}</summary><form onSubmit={e=>void save(e,true)} className="mt-4 space-y-3">{[[label('كلمة المرور الحالية','Current password'),current,setCurrent,'current-password'],[label('كلمة المرور الجديدة','New password'),password,setPassword,'new-password'],[label('تأكيد كلمة المرور الجديدة','Confirm new password'),confirm,setConfirm,'new-password']].map(([title,value,setter,auto],i)=><label key={i} className="block">{title as string}<input required type={show?'text':'password'} autoComplete={auto as string} minLength={i?12:1} maxLength={256} dir="ltr" className={textInputClassName(false)} value={value as string} onChange={e=>(setter as (s:string)=>void)(e.target.value)}/></label>)}<FormActions><Button type="button" variant="secondary" aria-pressed={show} onClick={()=>setShow(v=>!v)}>{show?label('إخفاء كلمات المرور','Hide passwords'):label('إظهار كلمات المرور','Show passwords')}</Button></FormActions><p className="text-sm text-muted">{label('١٢ حرفًا على الأقل. تغيير كلمة المرور يسجل خروج الجلسات الأخرى. البريد ورقم الهاتف لا يتغيران.','At least 12 characters. Changing your password signs out other sessions. Email and phone remain unchanged.')}</p><FormActions><Button type="submit" disabled={busy}>{label('حفظ كلمة المرور','Save password')}</Button></FormActions></form></details>
  </section>;
}
