import { useAuth } from '../../../auth';
import { useEffect, useState } from 'react';
import { apiFetch } from '../../../auth';
import { Button } from '../../../components/ui/Button';
import type { PublicContact } from './SupportSettings';
import { useLang } from '../../../i18n';
import { Container } from '../../../components/ui/Card';
import { Notice } from '../../../components/ui/Notice';

export function SupportPage():JSX.Element {
  const {lang}=useLang();const ar=lang==='ar';
  const [contact,setContact]=useState<PublicContact|null>(null);const [loading,setLoading]=useState(true);const [failed,setFailed]=useState(false);const [retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);setFailed(false);void apiFetch<{data:{contact:PublicContact|null}}>('/support/contact',{retryOnAuth:false}).then(r=>{if(active)setContact(r.data.contact);}).catch(()=>{if(active)setFailed(true);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[retry]);
  return <Container><main id="main" className="mx-auto max-w-3xl py-10 space-y-5"><h1 className="text-3xl font-bold">{ar?'المساعدة والدعم':'Help and support'}</h1><h2 className="text-xl font-bold">{ar?'الدخول وكلمة المرور':'Sign-in and password help'}</h2><p>{ar?'استعادة كلمة المرور حاليًا بمساعدة الإدارة. تواصل معنا بالبيانات أدناه، ولا تشارك كلمة المرور أو رموز الجلسة.':'Password recovery currently requires admin assistance. Contact us using the details below; never share passwords or session tokens.'}</p>
    {loading?<p role="status">{ar?'تحميل بيانات التواصل…':'Loading contact details…'}</p>:failed?<><Notice kind="error">{ar?'تعذر تحميل بيانات التواصل. حاول مجددًا.':'Could not load contact details. Please retry.'}</Notice><Button variant="secondary" onClick={()=>setRetry(n=>n+1)}>{ar?'إعادة المحاولة':'Retry'}</Button></>:contact?<dl data-testid="public-support-contact" className="space-y-3 rounded-card border border-border p-5"><div><dt>{ar?'البريد الإلكتروني':'Email'}</dt><dd><a dir="ltr" className="inline-block break-all underline" href={`mailto:${encodeURIComponent(contact.email)}`}>{contact.email}</a></dd></div><div><dt>{ar?'الهاتف':'Phone'}</dt><dd><a dir="ltr" className="inline-block underline" href={`tel:${contact.phone}`}>{contact.phone}</a></dd></div></dl>:<Notice kind="info">{ar?'لم تُضف بيانات تواصل الدعم بعد.':'Support contact details are not configured yet.'}</Notice>}
    {[[ar?'الشحن والاشتراك':'Recharge and access',ar?'تُراجع الإدارة إثبات التحويل قبل إضافة الرصيد. بعد الموافقة اختر الكورس واشترِ العرض المناسب.':'An admin verifies your transfer before crediting the wallet. After approval, choose a course and purchase the appropriate offer.','#/wallet'],[ar?'الدروس المقفلة':'Locked lessons',ar?'افتح التقييم المطلوب من قائمة الدروس واجتزه. المشاهدة تحتاج وصولًا ساريًا ونشر الكورس.':'Open the required assessment from the lesson outline and pass it. Playback needs active access and a published course.','#/dashboard'],[ar?'تشغيل الكود وإرسال الحل':'Run and Submit',ar?'التشغيل تجربة محلية. الإرسال يراجع الحل رسميًا؛ يمكنك إعادة المحاولة. التدريب اليومي منفصل عن التقييمات.':'Run is a local experiment. Submit checks your answer officially; you can retry. Daily practice is separate from assessments.','#/practice']].map(([title,text,href])=><section key={href} className="rounded-card border border-border p-5"><h2 className="font-bold">{title}</h2><p className="my-3">{text}</p><a href={href} className="underline">{ar?'فتح الصفحة':'Open page'}</a></section>)}
  </main></Container>;
}

const policyDrafts = [
  {key:'terms',ar:'شروط الاستخدام',en:'Terms of use',bodyAr:'FAYQ يقدم كورسات برمجة مسجلة. يشترط حساب طالب ووصول ساري للمشاهدة. يعرض كل عرض سعره وشروط مدته قبل الشراء. العربية والإنجليزية متاحتان. مطلوب من المالك: اسم الجهة القانونية وبيانات التواصل، شروط الأهلية وموافقة ولي الأمر عند الحاجة، حقوق استخدام المحتوى، قواعد الحساب والمنازعات والقانون المختص.',bodyEn:'FAYQ offers recorded programming courses. Viewing requires a student account and active access. Each offer displays its price and access terms before purchase. Arabic and English are available. Owner input required: legal entity/contact details, eligibility and any parental-consent requirements, content-use rights, account rules, dispute handling and governing law.'},
  {key:'privacy',ar:'الخصوصية',en:'Privacy',bodyAr:'تستخدم المنصة بيانات الحساب وسجلات الشحن والشراء والاشتراك وتقدم التعلم وحلول التقييم لتقديم الخدمة. رموز الجلسة في ملفات تعريف ارتباط؛ تفضيلات اللغة والمظهر تُحفظ في المتصفح. حماية الفيديو خدمة خارجية مستقلة. مطلوب من المالك: هوية مسؤول البيانات وطرق التواصل، أسماء مقدمي الخدمة الفعليين ومواقع المعالجة، مدد الاحتفاظ والأساس القانوني وحقوق الطلبات وسياسة بيانات القاصرين.',bodyEn:'The platform uses account information, recharge/purchase/subscription records, learning progress and assessment answers to provide the service. Session credentials use cookies; language/theme preferences are stored in the browser. Video protection is an independent external service. Owner input required: data-controller identity/contact, actual providers and processing locations, retention schedules, legal basis, request procedures and handling of minors\' information.'},
  {key:'refunds',ar:'الاسترداد',en:'Refunds',bodyAr:'الشحن يدوي بالجنيه المصري ويحتاج تحقق الإدارة قبل إضافة الرصيد. إيصال الشراء يحفظ السعر وشروط الوصول المدفوعة. لا تحدد هذه المسودة حقًا أو مهلة أو مبلغًا للاسترداد. مطلوب من المالك: شروط الأهلية والمهلة والاستثناءات وخطوات الطلب وقناة التواصل ومدة المعالجة وآلية الدفع، بعد المراجعة القانونية.',bodyEn:'Recharge is manual in EGP and requires admin verification before wallet credit. Purchase receipts retain paid price/access terms. This draft does not set a refund entitlement, deadline or amount. Owner input required after legal review: eligibility, time limits, exceptions, request steps/contact channel, processing time and payment method.'},
];
export function PolicyPage({kind,review=false}:{kind:string;review?:boolean}):JSX.Element {
  const {lang}=useLang();const ar=lang==='ar';const {user}=useAuth();
  return <Container><main id="main" className="mx-auto max-w-3xl py-10 space-y-5"><h1 className="text-3xl font-bold">{review?(ar?'مراجعة مسودات السياسات':'Policy draft review'):(policyDrafts.find(p=>p.key===kind)?.[ar?'ar':'en']??(ar?'السياسات':'Policies'))}</h1>{review && user?.role!=='ADMIN'?<Notice kind="error">{ar?'للإدارة فقط':'ADMIN only'}</Notice>:<><Notice kind="pending">{ar?'لم يعتمد المالك السياسات بعد. هذه الصفحات ليست شروطًا نافذة ولا سياسة استرداد معتمدة.':'The owner has not adopted the policies yet. These pages are not effective terms or an approved refund policy.'}</Notice>{review?policyDrafts.map(p=><section key={p.key} className="rounded-card border border-border p-5"><h2 className="text-xl font-bold">{ar?p.ar:p.en} — {ar?'مسودة للمراجعة':'Draft for review'}</h2><p className="my-3">{ar?p.bodyAr:p.bodyEn}</p></section>):<p>{ar?'النص المعتمد سيظهر بعد مراجعة المالك.':'Approved text will appear after owner review.'}</p>}<a href="#/support" className="underline">{ar?'المساعدة والدعم':'Help and support'}</a></>}</main></Container>;
}

export function NotFoundPage():JSX.Element {const {lang}=useLang();return <Container><main id="main" className="py-14"><h1 className="text-3xl font-bold">{lang==='ar'?'الصفحة غير موجودة':'Page not found'}</h1><p className="my-4">{lang==='ar'?'تحقق من الرابط أو انتقل إلى الكورسات.':'Check the link or browse the courses.'}</p><a className="underline" href="#/courses">{lang==='ar'?'تصفح الكورسات':'Browse courses'}</a></main></Container>;}
