import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { useLang } from '../../i18n';
import { Button } from '../../components/ui/Button';
import { Notice, Loading } from '../../components/ui/Notice';
import { textInputClassName } from '../../components/ui/Field';
import { assessmentApi, errorLabel } from './api';
import { EMPTY_SOURCE, type SourceFiles } from '../ide/types';
import { ProgramSettings, PreparationPanel, newProgram, type ProgramSettingsValue } from './ProgramSettings';
import { TypedValueEditor } from './TypedValueEditor';
import { AdminSubmissionReview } from './AdminSubmissionReview';
const WebIDE = lazy(() => import('../ide/WebIDE').then((m) => ({ default: m.WebIDE })));
interface Check { type: string; selector?: string; name?: string; expected?: unknown; args?: unknown[]; steps?: Array<{ action: string; selector: string; value?: string }> }
interface Question { id: string; type: 'CODING' | 'CHOICE' | 'PROGRAM'; program?: ProgramSettingsValue; titleAr: string; titleEn: string; starter?: SourceFiles; shareStarter?: boolean; checks?: Check[]; choices?: Array<{ id: string; textAr: string; textEn: string }>; correctChoiceId?: string }
interface Content { titleAr: string; titleEn: string; instructionsAr: string; instructionsEn: string; questions: Question[] }
interface Entry { id: string; lessonId: string; kind: string; required: boolean; draftRequired: boolean | null; status: string; content: Content; version: number }
const newQuestion = (type: 'CODING' | 'PROGRAM' = 'PROGRAM'): Question => ({ id: crypto.randomUUID(), type, titleAr: '', titleEn: '', starter: { ...EMPTY_SOURCE, javascript: '' }, shareStarter: false, ...(type === 'PROGRAM' ? { program: newProgram() } : { checks: [{ type: 'console', expected: '' }] }) });
export function AdminAssessmentPanel({ lessonId }: { lessonId: string }): JSX.Element {
  const { lang } = useLang(); const ar = lang === 'ar'; const label = (a: string, e: string): string => ar ? a : e;
  const [open, setOpen] = useState(false); const [list, setList] = useState<Entry[]>([]); const [editing, setEditing] = useState<string | null | false>(false);
  const [content, setContent] = useState<Content>({ titleAr: '', titleEn: '', instructionsAr: '', instructionsEn: '', questions: [] });
  const [kind, setKind] = useState('ASSIGNMENT'); const [required, setRequired] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [review, setReview] = useState<Entry | null>(null);
  const editor = useRef<HTMLDivElement>(null);
  const reload = async (): Promise<void> => { const r = await assessmentApi<{ assessments: Entry[] }>(`/admin/assessments/lessons/${lessonId}`); setList(r.assessments); };
  useEffect(() => { if (open) void reload().catch((e) => setError(errorLabel(e, ar))); }, [open, lessonId]);
  function edit(entry?: Entry): void { setEditing(entry?.id ?? null); setContent(entry?.content ?? { titleAr: '', titleEn: '', instructionsAr: '', instructionsEn: '', questions: [newQuestion()] }); setKind(entry?.kind ?? 'ASSIGNMENT'); setRequired(entry ? String(entry.draftRequired ?? entry.required) : ''); setReview(null); }
  function updateQuestion(index: number, q: Question): void { setContent((c) => ({ ...c, questions: c.questions.map((old, i) => i === index ? q : old) })); }
  async function save(): Promise<void> { if (busy || required === '') return; if (editor.current?.querySelector('[aria-invalid="true"]')) { setError(label('صحح القيم وأسماء الخصائص قبل الحفظ.', 'Correct the values and property names before saving.')); return; } setBusy(true); setError(''); try { await assessmentApi(editing ? `/admin/assessments/${editing}` : `/admin/assessments/lessons/${lessonId}`, editing ? 'PUT' : 'POST', { kind, required: required === 'true', content }); setEditing(false); await reload(); } catch (e) { setError(errorLabel(e, ar)); } finally { setBusy(false); } }
  async function transition(id: string, action: string): Promise<void> { if (busy) return; setBusy(true); setError(''); try { await assessmentApi(`/admin/assessments/${id}/${action}`, 'POST', {}); await reload(); } catch (e) { setError(errorLabel(e, ar)); } finally { setBusy(false); } }
  const input = (name: string, value: string, onChange: (v: string) => void, dir?: 'rtl' | 'ltr') => <label className="block"><span className="text-sm">{name}</span><input dir={dir} className={`${textInputClassName(false)} mt-1`} value={value} onChange={(e) => onChange(e.target.value)} /></label>;
  return <section data-testid={`assessment-admin-${lessonId}`} className="mt-4 border-t border-border pt-3"><Button variant="secondary" onClick={() => setOpen(!open)}>{label('الواجبات والاختبارات', 'Assignments and quizzes')}</Button>{open ? <div className="mt-3 space-y-4">
    {error ? <Notice kind="error">{error}</Notice> : null}
    {list.map((a) => <div key={a.id} className="flex flex-wrap items-center gap-2 rounded-control border border-border p-3"><strong>{ar ? a.content.titleAr : a.content.titleEn}</strong><span className="text-sm text-muted">{a.status === 'PUBLISHED' ? label('منشور', 'Published') : a.status === 'ARCHIVED' ? label('مؤرشف', 'Archived') : label('مسودة', 'Draft')} · {a.required ? label('مطلوب', 'Required') : label('اختياري', 'Optional')}</span><Button variant="secondary" onClick={() => edit(a)}>{label('تعديل', 'Edit')}</Button><Button disabled={busy} onClick={() => void transition(a.id, 'publish')}>{label('نشر النسخة', 'Publish revision')}</Button><Button disabled={busy} variant="secondary" onClick={() => void transition(a.id, 'archive')}>{label('أرشفة', 'Archive')}</Button><Button variant="secondary" onClick={() => { setEditing(false); setReview(a); }}>{label('الحلول المرسلة', 'Submissions')}</Button>{a.content.questions.some((q) => q.type === 'PROGRAM') ? <PreparationPanel key={JSON.stringify(a.content)} assessmentId={a.id} /> : null}</div>)}
    <Button variant="secondary" onClick={() => edit()}>{label('إضافة تقييم', 'Add assessment')}</Button>
    {editing !== false ? <div ref={editor} data-testid="assessment-editor" className="space-y-4 rounded-card border border-border bg-elevated p-4">
      <div className="grid gap-3 md:grid-cols-2">{input('العنوان بالعربية', content.titleAr, (v) => setContent({ ...content, titleAr: v }), 'rtl')}{input('Title in English', content.titleEn, (v) => setContent({ ...content, titleEn: v }), 'ltr')}
      <label>{label('التعليمات بالعربية', 'Arabic instructions')}<textarea dir="rtl" className={textInputClassName(false)} value={content.instructionsAr} onChange={(e) => setContent({ ...content, instructionsAr: e.target.value })} /></label><label>English instructions<textarea dir="ltr" className={textInputClassName(false)} value={content.instructionsEn} onChange={(e) => setContent({ ...content, instructionsEn: e.target.value })} /></label>
      <label>{label('نوع التقييم', 'Assessment type')}<select className={textInputClassName(false)} value={kind} onChange={(e) => setKind(e.target.value)}><option value="ASSIGNMENT">{label('واجب', 'Assignment')}</option><option value="QUIZ">{label('اختبار', 'Quiz')}</option></select></label>
      <label>{label('هل يلزم اجتيازه للمتابعة؟', 'Required to continue?')}<select required className={textInputClassName(false)} value={required} onChange={(e) => setRequired(e.target.value)}><option value="">{label('اختر', 'Choose')}</option><option value="true">{label('مطلوب', 'Required')}</option><option value="false">{label('اختياري', 'Optional')}</option></select></label></div>
      {content.questions.map((q, index) => <section key={q.id} className="space-y-3 rounded-control border border-border p-3"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{label('السؤال', 'Question')} {index + 1}</h3><select aria-label={label('نوع السؤال', 'Question type')} className={textInputClassName(false)} value={q.type} onChange={(e) => updateQuestion(index, e.target.value === 'CHOICE' ? { id: q.id, titleAr: q.titleAr, titleEn: q.titleEn, type: 'CHOICE', choices: [{ id: 'a', textAr: '', textEn: '' }, { id: 'b', textAr: '', textEn: '' }], correctChoiceId: '' } : { ...newQuestion(e.target.value === 'PROGRAM' ? 'PROGRAM' : 'CODING'), id: q.id, titleAr: q.titleAr, titleEn: q.titleEn })}><option value="PROGRAM">{label('مسألة مدخلات ومخرجات', 'Input/output problem')}</option><option value="CODING">{label('برمجة', 'Coding')}</option><option value="CHOICE">{label('اختيار من متعدد', 'Multiple choice')}</option></select><Button variant="secondary" onClick={() => setContent({ ...content, questions: content.questions.filter((_, i) => i !== index) })}>{label('حذف السؤال', 'Remove question')}</Button></div>
      <div className="grid gap-3 md:grid-cols-2">{input('السؤال بالعربية', q.titleAr, (v) => updateQuestion(index, { ...q, titleAr: v }), 'rtl')}{input('Question in English', q.titleEn, (v) => updateQuestion(index, { ...q, titleEn: v }), 'ltr')}</div>
      {q.type !== 'CHOICE' ? <>{q.type === 'PROGRAM' ? <ProgramSettings value={q.program!} onChange={(program) => updateQuestion(index, { ...q, program })} /> : null}<details><summary className="cursor-pointer">{label('كود JavaScript الخاص بالإدارة', 'Private admin JavaScript code')}</summary><Suspense fallback={<Loading text={label('تحميل المحرر…', 'Loading editor…')} />}><WebIDE value={q.starter!} onChange={(starter) => updateQuestion(index, { ...q, starter })} /></Suspense></details><label className="flex items-center gap-2"><input type="checkbox" checked={q.shareStarter === true} onChange={(e) => updateQuestion(index, { ...q, shareStarter: e.target.checked })} />{label('مشاركة هذا الكود ككود ابتدائي مع الطالب (لا تضع الحل الصحيح)', 'Share this code as student starter code (do not include the solution)')}</label><p className="text-sm text-muted">{label('الكود خاص بالإدارة افتراضيًا. الطالب يبدأ بمحرر فارغ؛ التقييم يعتمد على الاختبارات الخاصة.', 'Admin code is private by default. Students start with an empty editor; grading uses your private tests.')}</p>{q.type === 'CODING' ? <CheckBuilder checks={q.checks!} onChange={(checks) => updateQuestion(index, { ...q, checks })} /> : null}</> : <><div className="space-y-2">{q.choices?.map((c, i) => <div key={c.id} className="grid items-center gap-2 md:grid-cols-[1fr_1fr_auto]">{input('الخيار بالعربية', c.textAr, (v) => updateQuestion(index, { ...q, choices: q.choices!.map((x, j) => j === i ? { ...x, textAr: v } : x) }), 'rtl')}{input('Choice in English', c.textEn, (v) => updateQuestion(index, { ...q, choices: q.choices!.map((x, j) => j === i ? { ...x, textEn: v } : x) }), 'ltr')}<label><input type="radio" name={`correct-${q.id}`} checked={q.correctChoiceId === c.id} onChange={() => updateQuestion(index, { ...q, correctChoiceId: c.id })} /> {label('الإجابة الصحيحة', 'Correct answer')}</label></div>)}</div><Button variant="secondary" disabled={(q.choices?.length ?? 0) >= 8} onClick={() => updateQuestion(index, { ...q, choices: [...q.choices!, { id: crypto.randomUUID(), textAr: '', textEn: '' }] })}>{label('إضافة خيار', 'Add choice')}</Button></>}
      </section>)}
      <div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={content.questions.length >= 10} onClick={() => setContent({ ...content, questions: [...content.questions, newQuestion()] })}>{label('إضافة سؤال', 'Add question')}</Button><Button disabled={busy || required === ''} onClick={() => void save()}>{label('حفظ مسودة', 'Save draft')}</Button><Button variant="secondary" onClick={() => setEditing(false)}>{label('إلغاء', 'Cancel')}</Button></div>
    </div> : null}
    {review ? <AdminSubmissionReview key={review.id} assessmentId={review.id} title={ar ? review.content.titleAr : review.content.titleEn} onClose={() => setReview(null)} /> : null}
  </div> : null}</section>;
}

function CheckBuilder({ checks, onChange }: { checks: Check[]; onChange: (c: Check[]) => void }): JSX.Element {
  const { lang } = useLang(); const ar = lang === 'ar'; const label = (a: string, e: string): string => ar ? a : e;
  const update = (i: number, c: Check): void => onChange(checks.map((old, index) => index === i ? c : old));
  const show = (v: unknown): string => typeof v === 'string' ? v : v === undefined ? '' : JSON.stringify(v);
  return <div className="space-y-3"><h4 className="font-semibold">{label('اختبارات السلوك الخاصة', 'Private behavior checks')}</h4><p className="text-sm text-muted">{label('حدد مخرجات الطباعة أو ناتج الدالة. JavaScript فقط حاليًا؛ لا تقارن نص الكود.', 'Define console output or function results. JavaScript only for now; do not compare source text.')}</p>{checks.map((c, i) => <div key={i} className="space-y-2 rounded-control border border-border p-3">
    <label>{label('نوع الاختبار', 'Check type')}<select value={c.type} className={textInputClassName(false)} onChange={(e) => update(i, { type: e.target.value, ...(e.target.value !== 'console' && e.target.value !== 'function' ? { selector: '' } : {}), ...(e.target.value === 'function' ? { name: '', args: [], expected: '' } : e.target.value !== 'exists' ? { expected: '' } : {}) })}>{[...(!['console', 'function'].includes(c.type) ? [[c.type, 'اختبار صفحة سابق', 'Existing page check']] : []), ['console','مخرجات console.log','Printed output (console.log)'],['function','القيمة التي ترجعها الدالة','Function return value']].map(([v,a,e]) => <option key={v} value={v}>{label(a,e)}</option>)}</select></label>
    {!['console','function'].includes(c.type) ? <label>{label('محدد العنصر (مثل #result)', 'Element selector (e.g. #result)')}<input dir="ltr" className={textInputClassName(false)} value={c.selector ?? ''} onChange={(e) => update(i,{...c,selector:e.target.value})} /></label> : null}
    {['attribute','style','function'].includes(c.type) ? <label>{label('اسم الخاصية أو الدالة', 'Property or function name')}<input dir="ltr" className={textInputClassName(false)} value={c.name ?? ''} onChange={(e) => update(i,{...c,name:e.target.value})} /></label> : null}
    {c.type === 'function' ? <><p className="text-sm text-muted">{label('مثال: الدالة sum ومدخلان 2 و3 والناتج المتوقع رقم 5. كل مدخل قيمة منفصلة؛ لا تكتب اسم الدالة أو الأقواس في المدخلات.', 'Example: function sum, two inputs 2 and 3, expected Number 5. Each input is a separate value; do not enter the function name or parentheses as an input.')}</p><div className="space-y-3"><h5 className="font-semibold">{label('مدخلات الدالة', 'Function inputs')}</h5>{(c.args ?? []).map((argument, index) => <div key={index} className="rounded-control border border-border p-3"><TypedValueEditor name={label(`المدخل ${index + 1}`, `Input ${index + 1}`)} value={argument} onChange={(next) => update(i, { ...c, args: c.args!.map((old, at) => at === index ? next : old) })} /><Button variant="secondary" onClick={() => update(i, { ...c, args: c.args!.filter((_, at) => at !== index) })}>{label('حذف المدخل', 'Remove input')}</Button></div>)}<Button variant="secondary" disabled={(c.args?.length ?? 0) >= 10} onClick={() => update(i, { ...c, args: [...(c.args ?? []), ''] })}>{label('إضافة مدخل', 'Add input')}</Button></div></> : null}
    {['console', 'function'].includes(c.type) ? <TypedValueEditor name={label('القيمة المتوقعة', 'Expected value')} value={c.expected ?? (c.expected === null ? null : '')} consoleOutput={c.type === 'console'} onChange={(expected) => update(i, { ...c, expected })} /> : c.type !== 'exists' ? <label>{label('الناتج المتوقع (كما يظهر للطالب)', 'Expected output (as printed or displayed)')}<input dir="ltr" className={textInputClassName(false)} value={show(c.expected)} onChange={(e) => update(i,{...c,expected:e.target.value})} /></label> : null}
    {c.type === 'console' ? <p className="text-sm text-muted">{label('لطباعة console.log(2) اختر رقمًا وأدخل 2. للنص اختر نصًا واكتب Hello بدون علامات اقتباس. إذا توجد عدة طباعات، اختر نصًا وضع كل سطر كما يظهر.', 'For console.log(2), choose Number and enter 2. For text, choose Text and enter Hello without quotes. For several logs, choose Text and enter each output line exactly as displayed.')}</p> : null}{c.type === 'console' && typeof c.expected === 'string' && /^".*"$/.test(c.expected) ? <Notice kind="info">{label('علامات الاقتباس في هذا الحقل جزء من المخرجات المتوقعة. لطباعة 2 احذف علامات الاقتباس.', 'Quotation marks in this field are part of the expected output. To print 2, remove those quotation marks.')}</Notice> : null}{(!['console', 'function'].includes(c.type) || (c.steps?.length ?? 0) > 0) ? <Notice kind="info">{label('هذا الاختبار يحتوي على قواعد صفحة سابقة. JavaScript فقط حاليًا؛ احذف التفاعلات وحوّل القواعد إلى مخرجات أو ناتج دالة ثم احفظ وانشر. لا يتم حذف القواعد تلقائيًا.', 'This check contains earlier page rules. JavaScript is the current editor mode; remove interactions and use console or function checks, then save and publish. Existing rules are not removed automatically.')}</Notice> : null}{(c.steps ?? []).map((s,j) => <div key={j} data-testid="check-interaction" className="grid items-end gap-2 md:grid-cols-4"><select aria-label={label('تفاعل قبل الاختبار', 'Interaction before check')} value={s.action} className={textInputClassName(false)} onChange={(e) => update(i,{...c,steps:c.steps!.map((old,k)=>k===j?{...old,action:e.target.value}:old)})}><option value="click">{label('نقرة', 'Click')}</option><option value="input">{label('إدخال', 'Input')}</option></select><input dir="ltr" aria-label={label('عنصر التفاعل', 'Interaction selector')} className={textInputClassName(false)} value={s.selector} onChange={(e)=>update(i,{...c,steps:c.steps!.map((old,k)=>k===j?{...old,selector:e.target.value}:old)})} />{s.action==='input'?<input aria-label={label('القيمة المدخلة', 'Input value')} className={textInputClassName(false)} value={s.value??''} onChange={(e)=>update(i,{...c,steps:c.steps!.map((old,k)=>k===j?{...old,value:e.target.value}:old)})}/>:null}<Button variant="secondary" aria-label={label('حذف التفاعل', 'Remove interaction')} onClick={() => update(i, { ...c, steps: c.steps!.filter((_, index) => index !== j) })}>{label('حذف التفاعل', 'Remove interaction')}</Button></div>)}
    <div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>onChange(checks.filter((_,j)=>j!==i))}>{label('حذف الاختبار', 'Remove check')}</Button></div>
  </div>)}<Button variant="secondary" disabled={checks.length>=20} onClick={()=>onChange([...checks,{type:'console',expected:''}])}>{label('إضافة اختبار', 'Add check')}</Button></div>;
}

