/** Website UX proof against the owned synthetic Docker project only. */
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {lookup} from 'node:dns/promises';
import puppeteer from 'puppeteer-core';
const fixture=JSON.parse(fs.readFileSync('/evidence/m9-fixtures.json','utf8'));
const host=(await lookup('host.docker.internal')).address;
const browser=await puppeteer.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage',`--host-resolver-rules=MAP localhost ${host}`]});
const contexts=[];const errors=[];let checks=0;
const pass=(name,condition=true)=>{assert(condition,name);checks++;console.log(`PASS ${name}`);};
async function page(){const context=await browser.createBrowserContext();contexts.push(context);const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1280,height:900});await p.evaluateOnNewDocument(()=>{if(window.top===window)localStorage.setItem('edu-platform-lang','en');});return p;}
async function route(p,hash){await p.goto('http://localhost:8084/'+hash);}
async function login(p,email,password='m9 fixture password twelve words'){await route(p,'#/login');await p.waitForSelector('#login-id');await p.type('#login-id',email);await p.type('#login-password',password);await p.click('form button[type="submit"]');await p.waitForFunction(()=>location.hash==='#/account');}
async function click(p,text,scope='main'){assert(await p.evaluate(({text,scope})=>{const b=[...document.querySelector(scope).querySelectorAll('button')].find(e=>e.textContent.trim()===text);if(!b)return false;b.click();return true;},{text,scope}),`Missing button ${text}`);}
async function set(p,selector,value){await p.$eval(selector,(field,value)=>{Object.getOwnPropertyDescriptor(field.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));},value);}
async function api(p,path){return p.evaluate(async path=>{const r=await fetch('/api'+path,{credentials:'include'});return {status:r.status,body:await r.json()};},path);}
async function shot(p,name){await p.screenshot({path:`/evidence/ux-${name}.png`});}
try{
  const guest=await page();await route(guest,'#/login');await guest.waitForSelector('#login-password');await guest.type('#login-password','keep this password');await click(guest,'Show password','.form-card');
  pass('login password visibility preserves its entered value',await guest.$eval('#login-password',e=>e.type==='text' && e.value==='keep this password'));
  pass('login links directly to registration and recovery help',!!await guest.$('a[href="#/register"]') && !!await guest.$('a[href="#/support"]'));
  await route(guest,'#/register');await guest.waitForSelector('#reg-password');pass('signup links back to login and gives identifier examples',!!await guest.$('a[href="#/login"]') && await guest.$eval('#reg-email',e=>!!e.placeholder));
  await route(guest,'#/support');await guest.waitForFunction(()=>document.querySelector('main')?.textContent.includes('aliibrahim3600@gmail.com'));pass('support explains admin-assisted recovery with the current public contacts');await shot(guest,'support-en');
  await route(guest,'#/privacy');await guest.waitForFunction(()=>document.querySelector('main')?.textContent.includes('not adopted'));pass('unapproved policies are never presented as effective terms');
  await route(guest,'#/unknown-screen');await guest.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Page not found'));pass('unknown routes show a useful not-found page');

  const admin=await page();await login(admin,'m9-admin@example.test');await route(admin,'#/admin/students');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('20 students'));
  pass('admin directory displays a bounded first page');await click(admin,'Next');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Page 2'));pass('directory next page is available for populated records');
  await set(admin,'main input','m9-inactive');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('1 students'));pass('directory search resets pagination and identifies the student');await shot(admin,'directory-en');
  await route(admin,'#/admin/catalog');await admin.waitForSelector('#admin-search');pass('catalog starts with list/search and keeps creation closed',!await admin.$('#cf-slug'));
  await set(admin,'#admin-search','no-such-course');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('No matching courses'));pass('catalog search has useful no-results guidance');
  await click(admin,'Clear search and filters');await admin.waitForFunction(()=>!document.querySelector('#admin-search').value);pass('catalog filters have a clear reset');await shot(admin,'catalog-en');
  await route(admin,`#/admin/courses/${fixture.secondCourseId}`);await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Synthetic section 2'));pass('second populated course preserves two sections and four named lessons',await admin.$$eval('details[data-testid^="deletion-"]',es=>es.length===6));
  await route(admin,`#/admin/courses/${fixture.courseId}`);await admin.waitForSelector('[data-testid="course-workspace-tabs"]');pass('course opens in the lesson workspace without metadata/pricing overload',!await admin.$('#cf-slug') && !await admin.$('#plan-current'));
  const deletion=await admin.$eval(`[data-testid="deletion-${fixture.nextLessonId}"]`,e=>e.querySelector('summary').textContent);pass('lesson deletion identifies its lesson by name',deletion.includes('Lesson 2'));
  await admin.$eval(`[data-testid="deletion-${fixture.nextLessonId}"]`,e=>e.open=true);pass('lesson deletion uses UUID confirmation and remains disabled before exact input',await admin.$eval(`[data-testid="deletion-${fixture.nextLessonId}"]`,e=>e.textContent.includes('UUID') && e.querySelector('[data-testid="deletion-submit"]').disabled));
  await click(admin,'Publishing and actions');await admin.waitForSelector('[data-testid="course-readiness"]');pass('publishing has one archive action and a readiness checklist',await admin.$$eval('main button',bs=>bs.filter(b=>b.textContent.trim()==='Archive').length===1));await shot(admin,'course-publishing-en');await click(admin,'Archive');await admin.waitForFunction(()=>document.activeElement?.tagName==='BUTTON' && document.activeElement.closest('[role="dialog"]'));pass('archive confirmation focuses a real button',await admin.evaluate(()=>document.activeElement.textContent.trim()==='Archive'));await click(admin,'Cancel','[role="dialog"]');
  await click(admin,'Course details');await admin.waitForSelector('#cf-te');await set(admin,'#cf-te','Unsaved course title');let accept=false;let prompts=0;const dialog=async d=>{prompts++;accept?await d.accept():await d.dismiss();};admin.on('dialog',dialog);
  await click(admin,'Lessons and video');pass('course tab changes protect unsaved metadata',prompts===1 && await admin.$eval('#cf-te',e=>e.value==='Unsaved course title'));accept=true;await click(admin,'Lessons and video');await admin.waitForSelector('#cf-te',{hidden:true});admin.off('dialog',dialog);
  await admin.click('[aria-label="التبديل إلى العربية"]');await admin.setViewport({width:390,height:844});pass('Arabic course workspace fits a real mobile viewport',await admin.evaluate(()=>document.documentElement.dir==='rtl' && document.documentElement.scrollWidth<=innerWidth));
  pass('mobile section fields retain a usable full-width input',await admin.$eval('#sec-ta',e=>e.getBoundingClientRect().width>250));
  pass('Arabic business labels replace raw publication/media state',await admin.$eval('main',e=>!e.textContent.includes('PUBLISHED') && !e.textContent.includes('READY') && e.textContent.includes('الأقسام')));await shot(admin,'course-ar-mobile');
  await admin.click('[aria-label="Switch to English"]');await admin.setViewport({width:1280,height:900});
  await route(admin,'#/admin/packages');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Synthetic monthly package'));pass('populated package list loads with Refresh instead of Retry',await admin.$eval('main',e=>e.textContent.includes('Refresh packages') && !e.textContent.includes('Retry')));await shot(admin,'packages-en');
  await route(admin,'#/admin/policies');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Owner input required'));pass('admin policy review includes explicit owner decision placeholders');await shot(admin,'policy-drafts-en');

  const student=await page();await login(student,'m9-student@example.test');await route(student,`#/courses/m9-ui-course`);await student.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Continue learning'));pass('owned course offer leads directly to learning instead of a duplicate purchase');
  await route(student,`#/purchase/${fixture.planId}`);await student.waitForSelector('main a[href^="#/learn/"]');pass('already-owned checkout includes a continue-learning link');
  await route(student,'#/purchases');await student.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Web programming'));pass('purchase history shows a course name and receipt reference without changing paid terms',await student.$eval('main',e=>e.textContent.includes('Receipt reference') && e.textContent.includes('No expiry')));await shot(student,'purchases-en');
  await route(student,`#/package/${fixture.packageId}`);await student.waitForFunction(()=>document.querySelector('main')?.textContent.includes('cannot be watched'));pass('populated package detail explains its three members and presale access');await shot(student,'package-detail-en');
  await route(student,'#/wallet/recharge');await student.waitForFunction(()=>document.querySelector('main')?.textContent.includes('temporarily unavailable'));pass('unconfigured recharge disables all inputs before any impossible request',await student.$eval('main fieldset',e=>e.disabled));
  await route(student,'#/admin/students');await student.waitForFunction(()=>document.body.textContent.includes('ADMIN only'));pass('student cannot view the directory UI',!await student.$('main input'));
  await route(student,'#/admin/policies');await student.waitForFunction(()=>document.body.textContent.includes('ADMIN only'));pass('student cannot view admin policy drafts');

  await route(admin,'#/admin/recharge');await admin.waitForFunction(()=>document.querySelector('main')?.textContent.includes('Synthetic Student'));await click(admin,'Review');await admin.waitForSelector('[role="dialog"]');
  pass('populated recharge review shows proof, reference and exact transfer context',await admin.$eval('[role="dialog"]',e=>!!e.querySelector('img') && e.textContent.includes('Request reference') && e.textContent.includes('UXSYNTHETICTRANSFER')));
  pass('financial approval remains disabled until independent receipt verification',await admin.$$eval('[role="dialog"] button',bs=>bs.find(b=>b.textContent.includes('Confirm')).disabled));await shot(admin,'recharge-proof-en');
  const balanceBefore=(await api(student,'/wallet')).body.data.balancePiastres;
  await admin.click('[role="dialog"] input[type="checkbox"]');await admin.evaluate(()=>{[...document.querySelector('[role="dialog"]').querySelectorAll('button')].find(b=>b.textContent.includes('Confirm')).click();});
  await admin.waitForFunction(()=>document.querySelector('[role="dialog"]')?.textContent.includes('Approved and credited'));const balanceAfter=(await api(student,'/wallet')).body.data.balancePiastres;
  pass('synthetic manually verified approval credits exactly once',balanceAfter-balanceBefore===5000);pass('completed review prevents duplicate confirmation',await admin.$$eval('[role="dialog"] button',bs=>bs.find(b=>b.textContent.includes('Confirm')).disabled));

  const profile=await page();await login(profile,'m9-inactive@example.test');await route(profile,'#/account/profile');await profile.waitForSelector('[data-testid="account-settings"]');pass('account workspace exposes profile/security with distinct active states',await profile.evaluate(()=>!!document.querySelector('[data-testid="account-workspace"]') && !!document.querySelector('[data-testid="workspace-section-menu"]') && document.querySelector('[data-testid="account-workspace"] [href="#/account/profile"]')?.getAttribute('aria-current')==='page'));await set(profile,'[data-testid="account-settings"] > form input','Updated Student');await click(profile,'Save name','[data-testid="account-settings"]');await profile.waitForFunction(()=>document.querySelector('[data-testid="account-settings"]')?.textContent.includes('Your name was saved'));pass('profile name saves through the protected API');
  pass('save-name action group is centred relative to its panel',await profile.evaluate(()=>{const panel=document.querySelector('[data-testid="account-settings"] > form');const group=[...document.querySelectorAll('[data-testid="account-settings"] .form-actions')][0];if(!panel||!group)return false;const pr=panel.getBoundingClientRect();const gr=group.getBoundingClientRect();return Math.abs((pr.left+pr.right)/2-(gr.left+gr.right)/2)<24;}));
  const second=await page();await login(second,'m9-inactive@example.test');await profile.$eval('[data-testid="account-settings"] details',e=>e.open=true);const fields=await profile.$$('[data-testid="account-settings"] details input');await fields[0].type('incorrect current password');await fields[1].type('new browser password twelve words');await fields[2].type('new browser password twelve words');await click(profile,'Save password','[data-testid="account-settings"]');await profile.waitForFunction(()=>document.querySelector('[data-testid="error-feedback-stack"]')?.textContent.includes('current password'));
  pass('failed password change keeps entered values for correction',await profile.$eval('[data-testid="account-settings"] details input',e=>e.value==='incorrect current password'));
  await set(profile,'[data-testid="account-settings"] details input','m9 fixture password twelve words');await click(profile,'Save password','[data-testid="account-settings"]');await profile.waitForFunction(()=>document.querySelector('[data-testid="account-settings"]')?.textContent.includes('Other sessions were signed out'));
  pass('password change clears sensitive form fields after success',await profile.$$eval('[data-testid="account-settings"] details input',fields=>fields.every(f=>f.value==='')));pass('other browser session is revoked while this session remains usable',(await api(second,'/auth/me')).status===401 && (await api(profile,'/auth/me')).status===200);await shot(profile,'account-settings-en');
  pass('all added screens have no React/browser exceptions',errors.length===0);console.log(`Website UX checks=${checks} failed=0`);
}catch(e){console.error(e.stack);for(const c of contexts)for(const p of await c.pages()){console.error('PAGE',p.url(),await p.evaluate(()=>document.querySelector('main')?.textContent?.slice(0,2400)));await p.screenshot({path:'/evidence/ux-failure-'+contexts.indexOf(c)+'.png'});}process.exitCode=1;}finally{for(const c of contexts)await c.close();await browser.close();}
