import request from 'supertest';
import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { createWorld,registerStudent,studentDetailsFixture,csrfBootstrap,uniqueEmail,uniquePhone,uniqueIp,TEST_ORIGIN,TEST_PASSWORD,createTestAdmin,loginWith,type IdentityWorld,type Jar } from './identity-helpers.js';
let world:IdentityWorld;
const auth=(jar:Jar)=>({'Cookie':jar.header(),'Origin':TEST_ORIGIN,'X-Csrf-Token':jar.csrf(),'X-Forwarded-For':uniqueIp()});
beforeAll(async()=>{world=await createWorld();});afterAll(async()=>{await world.close();});
async function signup(extra:Record<string,unknown>={}){const {jar,token}=await csrfBootstrap(world.app);const body={displayName:'Synthetic Full Student Name',email:uniqueEmail(),phone:uniquePhone(),password:TEST_PASSWORD,...studentDetailsFixture(),...extra};const res=await request(world.app).post('/auth/register').set(auth(jar)).set('X-Csrf-Token',token).send(body);jar.setFrom(res);return {res,jar,body};}
describe('student onboarding and protected profile',()=>{
 it('persists encrypted ID and normalized required details, but excludes them from auth/session responses',async()=>{const {res,jar,body}=await signup({parentPhone:'٠١٠١٢٣٤٥٦٧٨'});expect(res.status).toBe(201);const stored=await world.prisma.studentProfile.findUniqueOrThrow({where:{userId:res.body.data.user.id}});expect(stored.parentPhone).toBe('+201012345678');expect(stored.nationalIdCipher).not.toContain(body.nationalId);expect(stored.nationalIdFingerprint).toHaveLength(64);const me=await request(world.app).get('/auth/me').set('Cookie',jar.header());expect(JSON.stringify([res.body,me.body])).not.toContain(body.nationalId);expect(me.body.data.user).not.toHaveProperty('studentProfile');const p=await request(world.app).get('/auth/student-profile').set('Cookie',jar.header());expect(p.status).toBe(200);expect(p.headers['cache-control']).toBe('no-store');expect(p.body.data.complete).toBe(true);expect(p.body.data.nationalIdMasked).toBe('**********'+body.nationalId.slice(-4));expect(p.body.data).not.toHaveProperty('nationalIdCipher');expect(p.body.data).not.toHaveProperty('nationalIdFingerprint');});
 it.each(['nationalId','parentPhone','schoolYear','governorate'])('requires %s for new registrations atomically',async field=>{const before=await world.prisma.user.count();const {res}=await signup({[field]:undefined});expect(res.status).toBe(400);expect(res.body.error.details.field).toBe(field);expect(await world.prisma.user.count()).toBe(before);});
 it('rejects normalized duplicates and reports no raw ID',async()=>{const first=await signup({nationalId:'29901010123456'});expect(first.res.status).toBe(201);const next=await signup({nationalId:'٢٩٩٠١٠١٠١٢٣٤٥٦'});expect(next.res.status).toBe(409);expect(next.res.body.error.code).toBe('NATIONAL_ID_TAKEN');expect(JSON.stringify(next.res.body)).not.toContain('29901010123456');expect(next.res.headers['set-cookie']).toBeUndefined();});
 it('allows one winner for concurrent registrations with the same ID, no orphan users/sessions',async()=>{const id=studentDetailsFixture().nationalId;const results=await Promise.all(Array.from({length:4},()=>signup({nationalId:id})));expect(results.map(r=>r.res.status).sort()).toEqual([201,409,409,409]);const emails=results.map(r=>r.body.email);expect(await world.prisma.user.count({where:{email:{in:emails}}})).toBe(1);expect(await world.prisma.authSession.count({where:{user:{email:{in:emails}}}})).toBe(1);});
 it('does not require unique guardian phone or a different student phone',async()=>{const phone=uniquePhone();const a=await signup({parentPhone:phone,phone});const b=await signup({parentPhone:phone});expect(a.res.status).toBe(201);expect(b.res.status).toBe(201);});
 it('keeps legacy accounts usable and permits one-time voluntary completion',async()=>{const owner=await signup();const userId=owner.res.body.data.user.id;await world.prisma.studentProfile.delete({where:{userId}});expect((await request(world.app).get('/auth/me').set('Cookie',owner.jar.header())).status).toBe(200);const p=await request(world.app).get('/auth/student-profile').set('Cookie',owner.jar.header());expect(p.body.data.complete).toBe(false);const update=await request(world.app).patch('/auth/student-profile').set(auth(owner.jar)).send({...studentDetailsFixture(),version:0});expect(update.status).toBe(200);expect(update.body.data.complete).toBe(true);expect(update.body.data.version).toBe(1);});
 it('allows contact/school edits but refuses student ID correction and stale saves',async()=>{const owner=await signup();const edit=await request(world.app).patch('/auth/student-profile').set(auth(owner.jar)).send({version:0,parentPhone:uniquePhone(),schoolName:'Updated school'});expect(edit.status).toBe(200);expect(edit.body.data.version).toBe(1);const stale=await request(world.app).patch('/auth/student-profile').set(auth(owner.jar)).send({version:0,schoolName:'Stale'});expect(stale.status).toBe(409);expect(stale.body.error.code).toBe('PROFILE_CHANGED');const forbidden=await request(world.app).patch('/auth/student-profile').set(auth(owner.jar)).send({version:1,nationalId:studentDetailsFixture().nationalId});expect(forbidden.status).toBe(403);expect(forbidden.body.error.code).toBe('NATIONAL_ID_ADMIN_ONLY');});
 it('requires auth, ADMIN and CSRF; ADMIN corrections enforce uniqueness and produce value-free audit',async()=>{const a=await signup(),b=await signup();const userId=a.res.body.data.user.id;expect((await request(world.app).get('/auth/student-profile')).status).toBe(401);expect((await request(world.app).get(`/admin/students/${userId}/profile`).set('Cookie',b.jar.header())).status).toBe(403);const admin=await createTestAdmin(world,'Profile Admin',TEST_PASSWORD);const login=await loginWith(world.app,admin.email);const path=`/admin/students/${userId}/profile`;expect((await request(world.app).get(path).set('Cookie',login.jar.header())).status).toBe(200);expect((await request(world.app).patch(path).set('Cookie',login.jar.header()).set('Origin',TEST_ORIGIN).send({version:0,nationalId:studentDetailsFixture().nationalId})).status).toBe(403);const conflict=await request(world.app).patch(path).set(auth(login.jar)).send({version:0,nationalId:b.body.nationalId});expect(conflict.status).toBe(409);expect(conflict.body.error.code).toBe('NATIONAL_ID_TAKEN');const id=studentDetailsFixture().nationalId;const fixed=await request(world.app).patch(path).set(auth(login.jar)).send({version:0,nationalId:id});expect(fixed.status).toBe(200);const events=await world.prisma.auditEvent.findMany({where:{entityId:userId}});expect(events.some(e=>e.action==='STUDENT_PROFILE_VIEWED')).toBe(true);expect(events.some(e=>e.action==='STUDENT_PROFILE_ADMIN_UPDATED')).toBe(true);expect(JSON.stringify(events)).not.toContain(id);expect(JSON.stringify(events)).not.toContain(a.body.nationalId);});
 it('fails new registration closed when keys are absent, while existing login still works',async()=>{const owner=await registerStudent(world.app);const noKeys=await createWorld({studentDataKeys:undefined});try{const {jar}=await csrfBootstrap(noKeys.app);const res=await request(noKeys.app).post('/auth/register').set(auth(jar)).send({displayName:'No Keys',email:uniqueEmail(),phone:uniquePhone(),password:TEST_PASSWORD,...studentDetailsFixture()});expect(res.status).toBe(503);expect(res.body.error.code).toBe('STUDENT_DATA_UNCONFIGURED');expect((await loginWith(noKeys.app,owner.user.email)).status).toBe(200);}finally{await noKeys.close();}});
 it('rejects mass assignment, malformed IDs and unknown selection values',async()=>{for(const extra of [{nationalId:'not-an-id'},{schoolYear:'garbage'},{governorate:'garbage'},{role:'ADMIN'}])expect((await signup(extra)).res.status).toBe(400);});
});
